import CONSTANTS from '../constants';
import { LightHUDElement, LightHUDPreset, VisionHUDElement, VisionHUDPreset } from '../lights-hud-ate-models';

export default {
  LIGHTS: <LightHUDElement[]>[
    {
      id: LightHUDPreset.NO_CHANGE,
      name: `${CONSTANTS.MODULE_NAME}.lights.${LightHUDPreset.NO_CHANGE}.name`,
      img: ``,
      lockRotation: null,
      dimLight: null,
      brightLight: null,
      lightColor: null,
      lightAlpha: null,
      lightAngle: null,
      lightAnimationType: null,
      lightAnimationSpeed: null,
      lightAnimationIntensity: null,
    },
    {
      id: LightHUDPreset.NONE,
      name: `${CONSTANTS.MODULE_NAME}.lights.${LightHUDPreset.NONE}.name`,
      img: ``,
      lockRotation: false,
      dimLight: 0,
      brightLight: 0,
      lightColor: null,
      lightAlpha: null,
      lightAngle: null,
      lightAnimationType: 'none',
      lightAnimationSpeed: null,
      lightAnimationIntensity: null,
    },
    {
      id: LightHUDPreset.CANDLE,
      name: `${CONSTANTS.MODULE_NAME}.lights.${LightHUDPreset.CANDLE}.name`,
      img: ``,
      lockRotation: false,
      dimLight: 10,
      brightLight: 5,
      lightColor: '#f8c377',
      lightAlpha: 0.15,
      lightAngle: 360,
      lightAnimationType: 'torch',
      lightAnimationSpeed: 2,
      lightAnimationIntensity: 2,
    },
    {
      id: LightHUDPreset.LAMP,
      name: `${CONSTANTS.MODULE_NAME}.lights.${LightHUDPreset.LAMP}.name`,
      img: ``,
      lockRotation: false,
      dimLight: 45,
      brightLight: 15,
      lightColor: '#f8c377',
      lightAlpha: 0.15,
      lightAngle: 360,
      lightAnimationType: 'torch',
      lightAnimationSpeed: 2,
      lightAnimationIntensity: 2,
    },
    {
      id: LightHUDPreset.LANTERN_BULLSEYE,
      name: `${CONSTANTS.MODULE_NAME}.lights.${LightHUDPreset.LANTERN_BULLSEYE}.name`,
      img: ``,
      lockRotation: false,
      dimLight: 120,
      brightLight: 60,
      lightColor: '#f8c377',
      lightAlpha: 0.15,
      lightAngle: 52.5,
      lightAnimationType: 'torch',
      lightAnimationSpeed: 2,
      lightAnimationIntensity: 2,
    },
    {
      id: LightHUDPreset.LANTERN_HOODED_DIM,
      name: `${CONSTANTS.MODULE_NAME}.lights.${LightHUDPreset.LANTERN_HOODED_DIM}.name`,
      img: ``,
      lockRotation: false,
      dimLight: 5,
      brightLight: 0,
      lightColor: '#f8c377',
      lightAlpha: 0.15,
      lightAngle: 360,
      lightAnimationType: 'torch',
      lightAnimationSpeed: 2,
      lightAnimationIntensity: 2,
    },
    {
      id: LightHUDPreset.LANTERN_HOODED_BRIGHT,
      name: `${CONSTANTS.MODULE_NAME}.lights.${LightHUDPreset.LANTERN_HOODED_BRIGHT}.name`,
      img: ``,
      lockRotation: false,
      dimLight: 60,
      brightLight: 30,
      lightColor: '#f8c377',
      lightAlpha: 0.15,
      lightAngle: 360,
      lightAnimationType: 'torch',
      lightAnimationSpeed: 2,
      lightAnimationIntensity: 2,
    },
    {
      id: LightHUDPreset.TORCH,
      name: `${CONSTANTS.MODULE_NAME}.lights.${LightHUDPreset.TORCH}.name`,
      img: `modules/${CONSTANTS.MODULE_NAME}/icons/ae/torch.jpg`,
      lockRotation: false,
      dimLight: 40,
      brightLight: 20,
      lightColor: '#f8c377',
      lightAlpha: 0.15,
      lightAngle: 360,
      lightAnimationType: 'torch',
      lightAnimationSpeed: 2,
      lightAnimationIntensity: 2,
    },
  ],
  VISIONS: <VisionHUDElement[]>[
    {
      id: VisionHUDPreset.NO_CHANGE,
      name: `${CONSTANTS.MODULE_NAME}.visions.${VisionHUDPreset.NO_CHANGE}.name`,
      img: ``,
      dimSight: null,
      brightSight: null,
      sightAngle: null,
    },
    {
      id: VisionHUDPreset.NONE,
      name: `${CONSTANTS.MODULE_NAME}.visions.${VisionHUDPreset.NONE}.name`,
      img: ``,
      dimSight: 0,
      brightSight: 0,
      sightAngle: 360,
    },
    {
      id: VisionHUDPreset.SELF,
      name: `${CONSTANTS.MODULE_NAME}.visions.${VisionHUDPreset.SELF}.name`,
      img: ``,
      dimSight: 5,
      brightSight: 0,
      sightAngle: 360,
    },
    {
      id: VisionHUDPreset.DARKVISION_30,
      name: `${CONSTANTS.MODULE_NAME}.visions.${VisionHUDPreset.DARKVISION_30}.name`,
      img: ``,
      dimSight: 30,
      brightSight: 0,
      sightAngle: 360,
    },
    {
      id: VisionHUDPreset.DARKVISION_60,
      name: `${CONSTANTS.MODULE_NAME}.visions.${VisionHUDPreset.DARKVISION_60}.name`,
      img: ``,
      dimSight: 60,
      brightSight: 0,
      sightAngle: 360,
    },
    {
      id: VisionHUDPreset.DARKVISION_90,
      name: `${CONSTANTS.MODULE_NAME}.visions.${VisionHUDPreset.DARKVISION_90}.name`,
      img: ``,
      dimSight: 90,
      brightSight: 0,
      sightAngle: 360,
    },
    {
      id: VisionHUDPreset.DARKVISION_120,
      name: `${CONSTANTS.MODULE_NAME}.visions.${VisionHUDPreset.DARKVISION_120}.name`,
      img: ``,
      dimSight: 120,
      brightSight: 0,
      sightAngle: 360,
    },
    {
      id: VisionHUDPreset.DARKVISION_150,
      name: `${CONSTANTS.MODULE_NAME}.visions.${VisionHUDPreset.DARKVISION_150}.name`,
      img: ``,
      dimSight: 150,
      brightSight: 0,
      sightAngle: 360,
    },
    {
      id: VisionHUDPreset.DARKVISION_180,
      name: `${CONSTANTS.MODULE_NAME}.visions.${VisionHUDPreset.DARKVISION_180}.name`,
      img: ``,
      dimSight: 180,
      brightSight: 0,
      sightAngle: 360,
    },
  ],
};
